### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by CestDiego** [lifelike/decide-mode#1]
Hi, I really like this and I would love to have it on a repository so people can easily install it on their own emacs configuration, have you considered/are working on making a PR to the [MELPA](https://github.com/milkypostman/melpa) repository?

I am more than willing to make this happen if you don't have the time for it now. 

kthxbai

**Comment by lifelike** [comment]
Thanks! I have really no idea how MELPA works and it is not something I plan to look into, but I would only be happy to see it happen.

**Comment by lifelike** [comment]
Merged!

It looked on the error-message also as if the file should be renamed to decide-mode.el? That sounds like an ok change as well if it is needed.
