### ISSUE TITLE
decide-make-dice-spec does not properly handle +0

### ISSUE THREAD

**Issue by mindfilleter** [lifelike/decide-mode#15]
When evaluating a dice spec, if the modifier is plus zero "+0" then the modifier should just be 0 and not parsed as the string "+0". It make look strange to report a result as "(3) +0 = 3" but when using decide-roll-dice-spec in an org-table cell formula, it's possible that the modifier may be calculated automatically and could be zero.

For example, in Dungeons & Dragons 5th edition, an attribute modifier is given by the formula:
```modifier = floor((attribute_score - 10) / 2)```

When the attribute score is exactly 10, the result is 0.

```
ELISP> (decide-make-dice-spec "1d3+1")
(1 3 1)

ELISP> (decide-make-dice-spec "1d3+0")
(1 3 "+0")

ELISP> (apply 'decide-roll-dice-spec (decide-make-dice-spec "1d3+1"))
"(3) +1 = 4"
ELISP> (apply 'decide-roll-dice-spec (decide-make-dice-spec "1d3+0"))
*** Eval error ***  Wrong type argument: number-or-marker-p, "+0"
```

**Comment by lifelike** [comment]
Thanks for reporting and fixing! Of course the 0 should be handled.
