### ISSUE TITLE
Fudge dice don't work.

### ISSUE THREAD

**Issue by AkashaRepo** [lifelike/decide-mode#17]
The documentation says this mode supports fudge dice, but when I try to use that feature, instead it gives the following output

```
[4d0] -> (79990312922493200 1516032711445625042 1698921923648616685 1109014288220209241) = -207726782190443736
```
This appears similar to issue https://github.com/lifelike/decide-mode/issues/5 where unknown die notation produces similar results.

**Comment by lifelike** [comment]
Made an attempt to fix dice-parsing and clean up the code, but it still has some issues (currently the old problem with "+0" is back for instance). Will post something when it works as it should. Thanks for reporting this! I have used regular die-rolls a lot, but not the custom dice.

**Comment by AkashaRepo** [comment]
This is what git hub is for! The rest of the internet gets to beta test for free.

**Comment by lifelike** [comment]
I pushed a new branch with some tests and a fix for dice that seems to work (but my elisp for parsing numbers is a mess right now!): https://github.com/lifelike/decide-mode/tree/ert-0.10.0
