### ISSUE TITLE
Tables need weights!

### ISSUE THREAD

**Issue by dustinlacewell-wk** [lifelike/decide-mode#6]
![image](https://user-images.githubusercontent.com/30800610/37371691-3098b90c-26de-11e8-9ac6-99f651dbccdd.png)

**Comment by lifelike** [comment]
Fully agree. I remember looking at it, but do not remember if it ended up on a branch or if I just remove what little code I had. I had some idea about how a number before each table entry would work without much change (and be backwards-compatible, in case someone actually has some old table they want to keep). But it would be a bit of ramp-up for me to get back into this project right now. PRs welcome though.

**Comment by lifelike** [comment]
Thanks! Opening a new issue for seq-reduce in emacs24.
